<?php

namespace AppBundle\Repository;

/**
 * GradingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GradingRepository extends \Doctrine\ORM\EntityRepository
{
}
