<?php

namespace AppBundle\Repository;

/**
 * ScoreChildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreChildRepository extends \Doctrine\ORM\EntityRepository
{
    public function childIsAlreadyRecorded($student, $class, $childSubject, $examCompany)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.student = :student')
            ->andWhere('a.class = :class')
            ->andWhere('a.childSubject = :childSubject')
            ->andWhere('a.examCompany = :examCompany')
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1)
            ->setParameter('student', $student)
            ->setParameter('class', $class)
            ->setParameter('childSubject', $childSubject)
            ->setParameter('examCompany', $examCompany)
            ->getQuery()
            ->getOneOrNullResult();
    }	
	
}
