<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function countStudents($user)
    {
        return $this->createQueryBuilder('s')
            ->select('count(s.id)')
            ->where('s.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult();
    }

	public function getPreviousStudent($studentId)
	{
	    return $this->createQueryBuilder('u')
	        ->select('u')

	        // Filter users.
	        ->where('u.id < :studentId')
	        ->setParameter(':studentId', $studentId)

	        // Order by id.
	        ->orderBy('u.id', 'DESC')

	        // Get the first record.
	        ->setFirstResult(0)
	        ->setMaxResults(1)
            ->getQuery()
	        ->getOneOrNullResult()
	    ;

	}

	public function getNextStudent($studentId)
	{
	    return $this->createQueryBuilder('u')
	        ->select('u')

	        ->where('u.id > :studentId')
	        ->setParameter(':studentId', $studentId)

	        ->orderBy('u.id', 'ASC')

	        ->setFirstResult(0)
	        ->setMaxResults(1)
            ->getQuery()
	        ->getOneOrNullResult()
	    ;

	}	

}
