<?php

namespace AppBundle\Repository;

/**
 * FormulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaRepository extends \Doctrine\ORM\EntityRepository
{
}
