<?php

namespace AppBundle\Repository;

/**
 * ScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoreRepository extends \Doctrine\ORM\EntityRepository
{
    public function isAlreadyRecorded($student, $class, $subject, $examCompany)
    {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.student = :student')
            ->andWhere('a.class = :class')
            ->andWhere('a.subject = :subject')
            ->andWhere('a.examCompany = :examCompany')
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1)
            ->setParameter('student', $student)
            ->setParameter('class', $class)
            ->setParameter('subject', $subject)
            ->setParameter('examCompany', $examCompany)
            ->getQuery()
            ->getOneOrNullResult();
    }   


}

