<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ChildSubject extends \AppBundle\Entity\ChildSubject implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'cSTitle', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'out_of', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'subject', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'scoreChildren'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'cSTitle', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'out_of', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'subject', '' . "\0" . 'AppBundle\\Entity\\ChildSubject' . "\0" . 'scoreChildren'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ChildSubject $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCSTitle($cSTitle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCSTitle', [$cSTitle]);

        return parent::setCSTitle($cSTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getCSTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCSTitle', []);

        return parent::getCSTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\AppBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubject(\AppBundle\Entity\Subject $subject = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubject', [$subject]);

        return parent::setSubject($subject);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubject', []);

        return parent::getSubject();
    }

    /**
     * {@inheritDoc}
     */
    public function setOutOf($outOf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOutOf', [$outOf]);

        return parent::setOutOf($outOf);
    }

    /**
     * {@inheritDoc}
     */
    public function getOutOf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutOf', []);

        return parent::getOutOf();
    }

    /**
     * {@inheritDoc}
     */
    public function addScoreChild(\AppBundle\Entity\ScoreChild $scoreChild)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addScoreChild', [$scoreChild]);

        return parent::addScoreChild($scoreChild);
    }

    /**
     * {@inheritDoc}
     */
    public function removeScoreChild(\AppBundle\Entity\ScoreChild $scoreChild)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeScoreChild', [$scoreChild]);

        return parent::removeScoreChild($scoreChild);
    }

    /**
     * {@inheritDoc}
     */
    public function getScoreChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScoreChildren', []);

        return parent::getScoreChildren();
    }

}
